# Generated by Django 4.2.14 on 2024-07-31 20:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_category_slug_product_slug_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True, verbose_name="Slug"
            ),
        ),
    ]
